CREATE TABLE usuario (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
     nome VARCHAR(255),
     email VARCHAR(255),
     avatar_url VARCHAR(255),
     CONSTRAINT pk_usuario PRIMARY KEY (id),
     CONSTRAINT uc_usuario_email UNIQUE (email)
);